# https://taskfile.dev

version: '3'

vars:
  check_dirs: .
  test_dirs: ./internal

tasks:
  check:
    cmds:
      - gofmt -w {{.check_dirs}}

  modules:
    deps: [test]
    cmds:
      - go mod tidy
    aliases: [mod]

  build:
    deps: [modules]
    cmds:
      - go build .

  run:
    deps: [build]
    cmds:
      - go run .
  
  test:
    cmds:
      - go test {{.test_dirs}}
